Feature/inline css
infinum/eightshift-forms pull request #224
Opened 2022-04-21 19:41 UTC by iruzevic

# Description

- fixing phpstan
- fixing phpcs
- merging @mbmjertan PR

2022-04-21 19:43 UTC, iruzevic commented
@mbmjertan is there a chance you can fix 2 test issues before we release

tnx

2022-04-22 08:05 UTC, volfkarlo requested changes
Minor changes/suggestions.
Well done 👏 🎉

2022-04-22 08:05 UTC, volfkarlo commented on tests/Validation/ValidatorTest.php
> +]);
Missing empty line

2022-04-22 08:05 UTC, volfkarlo commented on tests/Validation/ValidationSettingsTest.php
> +});
Missing empty line

2022-04-22 08:05 UTC, volfkarlo commented on tests/Helpers.php
two lines at the end

2022-04-22 08:05 UTC, volfkarlo commented on tests/Hooks/FiltersTest.php
> +})->throws(MissingFilterInfoException::class);
no empty line

2022-04-22 08:05 UTC, volfkarlo commented on tests/Hooks/FiltersTest.php
> +
double new line

2022-04-22 08:05 UTC, volfkarlo commented on tests/Mailer/MailerTest.php
> +]);
no empty line

2022-04-22 08:05 UTC, volfkarlo commented on tests/Permissions/PermissionsTest.php
> +});
no empty line

2022-04-22 08:08 UTC, mbmjertan commented
@iruzevic yes, sure, I'll check what's going on there

2022-04-22 08:10 UTC, mbmjertan commented on src/Integrations/Clearbit/ClearbitClient.php
> +		$code = $response['response']['code'] ? $response['response']['code'] : 200;
This is discouraged by Eightshift Coding Standards, IIRC.

2022-04-22 08:11 UTC, mbmjertan commented on src/Integrations/Greenhouse/GreenhouseClient.php
> +		$output = \get_transient(self::CACHE_GREENHOUSE_ITEMS_TRANSIENT_NAME) ?: []; // phpcs:ignore WordPress.PHP.DisallowShortTernary.Found
😄

2022-04-22 13:23 UTC, iruzevic commented on src/Blocks/assets/styles/application-blocks-frontend.scss
> +// @import './../../custom/*/*-frontend.scss';
these are placeholders like in the boilerplate.

2022-04-22 13:34 UTC, mbmjertan approved these changes

2022-04-24 07:56 UTC, dingo-d approved these changes

2022-04-25 07:15 UTC, merged