Mailer update
infinum/eightshift-forms pull request #226
Opened 2022-04-28 18:45 UTC by gabriel-glo

# Description

Allow adding template tags to other fields in Mailer settings (destination email, subject, confirmation email, .etc)

# Screenshots / Videos

![image](https://user-images.githubusercontent.com/41635034/165824345-9910e536-758e-4a18-a928-f14a89aecab3.png)

2022-04-28 20:13 UTC, mbmjertan approved these changes
Looks good to me, but it would be great to add tests for this. (I can do that as well if you'd like)

2022-05-03 10:12 UTC, dingo-d commented on tests/Mailer/MailerSettingsTest.php
> +	$this->assertSame(true, $this->mailerSettings->isSettingsValid('1234'));
```suggestion
	expect($this->mailerSettings->isSettingsValid('1234'))->toBeTrue();
```

2022-05-03 10:13 UTC, dingo-d commented on tests/Mailer/MailerSettingsTest.php
> +	expect($this->mailerSettings->getSettingsSidebar())->toHaveKeys(['label', 'value', 'icon']);
Expectations are chainable

```suggestion
	expect($this->mailerSettings->getSettingsSidebar())
		->toBeArray()
		->toHaveKeys(['label', 'value', 'icon']);
```

😉

2022-05-03 10:14 UTC, dingo-d commented on tests/Mailer/MailerSettingsTest.php
>  	$this->assertSame(10, \has_filter(SettingsMailer::FILTER_SETTINGS_IS_VALID_NAME, 'EightshiftForms\Mailer\SettingsMailer->isSettingsValid()'), 'The callback isSettingsValid should be hooked to custom
Can you convert this to expectations API? 🙏🏼

2022-05-03 10:22 UTC, dingo-d requested changes
Expectations api replacement

2022-05-03 10:37 UTC, iruzevic approved these changes
Feature looks good, fix Test comments

2022-05-03 11:40 UTC, dingo-d approved these changes

2022-05-03 11:44 UTC, dadadavorin approved these changes

2022-05-04 11:55 UTC, merged