Append merge_fields to body only if not empty
infinum/eightshift-forms pull request #237
Opened 2022-06-09 12:42 UTC by dadadavorin

# Description

Mailchimp request was breaking if `$body[merge_fields]` inside MailchimpClient `postApplication` function contained empty array. 

This will append `merge_fields` to output only if it is not empty, which solves the issue.

2022-06-09 12:46 UTC, iruzevic requested changes

2022-06-09 12:46 UTC, iruzevic commented on src/Integrations/Mailchimp/MailchimpClient.php
> +		if (!empty($this->prepareParams($params))) {
the same comment apply please make this little better

2022-06-09 13:17 UTC, dingo-d approved these changes

2022-06-09 13:18 UTC, dingo-d requested changes
I'm stupid. Please fix tests and CI checks 🙏🏼

2022-06-23 13:23 UTC, gabriel-glo approved these changes

2022-06-28 06:36 UTC, dingo-d approved these changes

2022-06-28 08:11 UTC, merged