Forms v4 visual refresh
infinum/eightshift-forms pull request #299
Opened 2023-04-25 13:16 UTC by goranalkovic-infinum

Changes:
- totally reworked admin and block editor UIs
- cleaned up some parts
- improved UI and UX

Protip: go commit by commit 😄

![image](https://user-images.githubusercontent.com/77000136/234288121-574b7f04-92a6-40f9-9501-fcf59e7e97fa.png)

2023-04-25 13:17 UTC, iruzevic approved these changes

2023-04-25 14:06 UTC, piqusy requested changes
Wow, the improvement is gigantic, great job overall 🚀 
I haven't checked everything, "only" checked 100 files 😄 

I left some suggestions in the comments and please fix linter errors.

Also I've notice you are using `px`, `rem` & `em` values intermittently in the admin area.
Is there a reason why you couldn't use a same unit? The 1px is for borders and such is fine IMO

P.S. I see some commits were made while I was reviewing, please ignore what I commented on if it is already fixed

2023-04-26 07:19 UTC, goranalkovic-infinum commented on src/Blocks/components/admin-settings-section/admin-settings-section-admin.scss
>  				duration: 0.3s;
Nope, it should use the first one for all of 'em.

2023-04-26 07:19 UTC, goranalkovic-infinum commented on src/Blocks/components/card/card-admin.scss
> +				gap: 0.5ch;
All intented 😄

2023-04-26 07:20 UTC, goranalkovic-infinum commented on src/Blocks/components/conditional-tags/components/conditional-tags-forms-options.js
> +									<Button
A bit of visual separation, whitespace doesn't cost anything 😛

2023-04-26 09:21 UTC, iruzevic approved these changes

2023-04-26 09:35 UTC, piqusy requested changes
Looking good, left some minor suggestions for some of the files I haven't had a change to review the last time😊

2023-04-26 09:35 UTC, piqusy commented on src/Blocks/components/submit/submit-admin.scss
>  button.es-submit {
Could you nest `.es-submit`

2023-04-26 09:35 UTC, piqusy commented on src/Blocks/components/submit/submit-editor.scss
> +button.es-submit {
Please nest `.es-submit`

2023-04-26 09:35 UTC, piqusy commented on src/Blocks/components/submit/submit-style.scss
>  button.es-submit {
Same as above

2023-04-26 10:10 UTC, piqusy approved these changes
Approved ... Haven't checked all the files tho' 😄

2023-04-26 10:19 UTC, merged