addings fixes for debug
infinum/eightshift-forms pull request #334
Opened 2023-10-25 13:57 UTC by iruzevic

# Description

* If you have developed tools active, it will output this new warning in the top nav bar
* We have a new development key to use the Query Monitor plugin output log to show data that are pulled from the external API using PHP.
* All development checks now also check if the top level Dashboard key is active, so you can turn off the main feature and everything else will turn off

![Screenshot 2023-10-25 at 15 36 27](https://github.com/infinum/eightshift-forms/assets/23283324/c8df9b33-8bb9-4e09-aa24-77daab194203)
![Screenshot 2023-10-25 at 15 36 37](https://github.com/infinum/eightshift-forms/assets/23283324/9ad02d12-0a70-458f-91ef-70248cc86ee4)
![Screenshot 2023-10-25 at 15 37 55](https://github.com/infinum/eightshift-forms/assets/23283324/c2b51c9e-d655-4933-803b-0a7ab4f5e466)

2023-10-25 14:08 UTC, kancijan approved these changes

2023-10-25 14:11 UTC, goranalkovic-infinum requested changes

2023-10-25 14:11 UTC, goranalkovic-infinum commented on src/AdminMenus/FormAdminBarMenu.php
> +					'title' => ($isDevelopMode || $isDevelopModeQmLog) ? \esc_html__('Your Debug tools are active!', 'eightshift-forms') : $mainLabel,
```suggestion
					'title' => ($isDevelopMode || $isDevelopModeQmLog) ? \esc_html__('Debug tools are active!', 'eightshift-forms') : $mainLabel,
```

2023-10-25 14:11 UTC, goranalkovic-infinum commented on src/Blocks/components/admin-top-menu-bar/admin-top-menu-bar-admin.scss
> +	color: red;
```suggestion
	color: #FF6900;
```

2023-10-25 14:19 UTC, piqusy requested changes
Lovely improvement 👏🏼 

Left two suggestions for your consideration

2023-10-25 14:32 UTC, dadadavorin approved these changes

2023-10-26 06:14 UTC, iruzevic commented on src/Blocks/components/admin-top-menu-bar/admin-top-menu-bar-admin.scss
> +	color: red;
it actually is really important as you can leak sensitive information to an unauthorized users

2023-10-26 06:15 UTC, merged