Feature/pre post
infinum/eightshift-forms pull request #341
Opened 2023-11-15 13:46 UTC by iruzevic

# Description

- adding new filter for overriding integration ID
- adding local storage save for field values
- adding prefill for field from url
- bugfixes

2023-11-15 14:16 UTC, iobrado requested changes
One minor change

2023-11-15 14:16 UTC, iobrado commented on testFilters/testFilters.php
> +	 */
```suggestion
	/**
	 * Change integration ID fields data before we send it to the external integration.
	 *
	 * @param string $itemId Item id.
	 * @param array<mixed> $params Params to alterate.
	 * @param string $formId Form id.
	 *
	 * @return string
	 */
```

Double docblock comment

2023-11-15 15:04 UTC, piqusy requested changes
Nice work 👏🏼 

I have just one question / suggestion

2023-11-15 16:03 UTC, iruzevic commented on testFilters/testFilters.php
> +	 */
tnx

2023-11-15 16:03 UTC, iruzevic commented on src/Blocks/components/form/assets/form.js
>  				enableTime: this.state.getStateElementTypeInternal(name, formId) === 'datetime',
yes I have updated it tnx

2023-11-16 06:42 UTC, kancijan approved these changes

2023-11-16 08:46 UTC, goranalkovic-infinum requested changes

2023-11-16 08:46 UTC, goranalkovic-infinum commented on src/Blocks/components/form/assets/utilities.js
> +		console.log(input, custom, value);
👀

2023-11-16 08:46 UTC, goranalkovic-infinum commented on src/Blocks/components/form/assets/utilities.js
> +		console.log(formId, name, value);
👀

2023-11-16 08:46 UTC, goranalkovic-infinum commented on src/Blocks/components/form/assets/utilities.js
> +			// console.log(innerInput, innerValue);
👀

2023-11-16 14:03 UTC, merged