Feature/airtable
infinum/eightshift-forms pull request #381
Opened 2024-02-22 15:59 UTC by iruzevic

### Added
- New `dynamic` block and component to allow dynamic form fields.
- Integration form picker now supports clear option.
- Airtable integration now supports dynamic connected tables.
- Airtable integration now supports multiple select fields.

### Fixed
- Integration sync fix when you unset attributes that are set in manifest as default.

2024-02-22 16:07 UTC, goranalkovic-infinum requested changes
![Toeto](https://media1.tenor.com/m/Bi7HgrmMxmEAAAAd/ceca-cista-egzotika.gif)

2024-02-22 16:07 UTC, goranalkovic-infinum commented on src/Blocks/components/dynamic/components/dynamic-editor.js
> +		selector(componentClass, componentClass),
Please use `classnames` from Libs

2024-02-22 16:07 UTC, goranalkovic-infinum commented on src/Blocks/components/dynamic/components/dynamic-options.js
> +				label={__('Is Deactivated', 'eightshift-forms')}
```suggestion
				label={__('Deactivated', 'eightshift-forms')}
```

2024-02-22 16:07 UTC, goranalkovic-infinum commented on src/Blocks/components/dynamic/components/dynamic-options.js
> +							type={'dynamic'}
```suggestion
							type='dynamic'
```

2024-02-22 16:07 UTC, goranalkovic-infinum commented on src/Blocks/components/integrations/components/integrations-options.js
> +						clearable={true}
```suggestion
						clearable
```

2024-02-22 16:07 UTC, goranalkovic-infinum commented on src/Blocks/components/integrations/components/integrations-options.js
> +							clearable={true}
```suggestion
							clearable
```

2024-02-22 16:07 UTC, goranalkovic-infinum commented on src/Integrations/Airtable/Airtable.php
> +						'dynamicCustomLabel' => \sprintf(\__('We will display dinamic data on the frontend for %1$s field - %2$s.', 'eightshift-forms'), $label, $name),
```suggestion
						'dynamicCustomLabel' => \sprintf(\__('We will display dynamic data on the frontend for %1$s field - %2$s.', 'eightshift-forms'), $label, $name),
```

2024-02-22 16:15 UTC, kancijan approved these changes

2024-02-23 07:39 UTC, kancijan approved these changes

2024-02-23 08:42 UTC, goranalkovic-infinum approved these changes

2024-02-23 09:02 UTC, merged