Updating hotfixes for forms
infinum/eightshift-forms pull request #394
Opened 2024-03-14 15:51 UTC by iruzevic

### Fixed
- single submit on calculation forms will now send all form data on submit.
- range current state will now update on initial load.

2024-03-14 15:59 UTC, dingo-d approved these changes

2024-03-14 16:05 UTC, goranalkovic-infinum requested changes

2024-03-14 16:05 UTC, goranalkovic-infinum commented on src/Blocks/components/form/assets/form.js
> +			), 100);
```suggestion
			debounce(this.formSubmit(formId), 100);
```
Change others as well pls, it's hard to read when strung over 4 lines

2024-03-15 06:27 UTC, dingo-d approved these changes

2024-03-15 06:50 UTC, merged