Feature/talentlyft
infinum/eightshift-forms pull request #439
Opened 2024-08-07 12:16 UTC by iruzevic

### Added

- New TalentLyft integration.

2024-08-07 12:33 UTC, goranalkovic-infinum submitted a review, later dismissed

2024-08-07 12:40 UTC, piqusy requested changes
Nice work 👏🏼 

Left a few suggestions

2024-08-07 12:40 UTC, piqusy commented on src/Blocks/custom/talentlyft/manifest.json
> +	},
Can be removed?

2024-08-07 12:40 UTC, piqusy commented on src/Integrations/Talentlyft/SettingsTalentlyft.php
> +								'inputFieldHelp' => \__('Up to 5MB.', 'eightshift-forms'),
Can the value of `self::SETTINGS_TALENTLYFT_FILE_UPLOAD_LIMIT_KEY` be `sprint_f`...ed here? 😄

2024-08-07 12:40 UTC, piqusy commented on src/Integrations/Talentlyft/TalentlyftClient.php
> +	 * @param bool $hideUpdateTime Determin if update time will be in the output or not.
```suggestion
	 * @param bool $hideUpdateTime Determine if update time will be in the output or not.
```

2024-08-07 12:40 UTC, piqusy commented on src/Rest/Routes/Integrations/Talentlyft/IntegrationItemsTalentlyftRoute.php
> +					\esc_html__('Global not configured', 'eightshift-forms'),
```suggestion
					\esc_html__('Global settings not configured', 'eightshift-forms'),
```

2024-09-03 11:30 UTC, goranalkovic-infinum approved these changes

2024-09-03 11:50 UTC, piqusy approved these changes

2024-09-03 11:57 UTC, merged