More value types supported in Countries
infinum/eightshift-forms pull request #442
Opened 2024-08-14 10:39 UTC by mbmjertan

# Description

I added a new "value type" attribute to the country field and use it to define the option values accordingly. I have adapted the Countries class to support this, but I am not sure whether I need to additionally change existing datasets and whether this covers custom datasets and the hidden value implementation we've discussed.

To do (on my end):
- [ ] Check "custom country list" functionality support
- [ ] Test out on staging instances with integrations
- [ ] Check hidden field support

Linked to 1777, iruzevic knows in which repo 😄 

# Screenshots / Videos

<img width="395" alt="Screenshot 2024-08-14 at 12 37 02" src="https://github.com/user-attachments/assets/52a0a2d3-110f-464d-bb80-9459dbb71bd4">

# Linked documentation PR

N/A

2024-08-14 10:41 UTC, mbmjertan reviewed
it's easier this way

2024-08-14 10:41 UTC, mbmjertan commented on src/Blocks/components/country/components/country-options.js
> +					onChange={(value) => {setAttributes({ [getAttrKey('countryIsRequired', attributes, manifest)]: value })}}
```suggestion
					onChange={(value) => setAttributes({ [getAttrKey('countryIsRequired', attributes, manifest)]: value })}
```

2024-08-14 10:41 UTC, mbmjertan commented on src/Blocks/components/country/components/country-options.js
> +	STORE_NAME, Select,
```suggestion
	STORE_NAME, 
	Select,
```

2024-08-14 10:43 UTC, iruzevic approved these changes

2024-08-14 10:43 UTC, iruzevic commented
looking good 👍 great work

2024-08-14 10:50 UTC, kancijan requested changes

2024-08-14 10:50 UTC, kancijan commented on src/Blocks/components/country/country.php
> +		$value = $option[2] ?? ''; // country phone code
```suggestion
		$value = $option[2] ?? ''; // Country phone code.
```

2024-08-14 13:42 UTC, kancijan approved these changes

2024-08-16 07:07 UTC, goranalkovic-infinum approved these changes

2024-08-19 10:19 UTC, piqusy approved these changes

2024-08-19 11:28 UTC, dingo-d approved these changes

2024-08-27 11:28 UTC, merged