adding once feature
infinum/eightshift-forms pull request #455
Opened 2024-11-11 14:22 UTC by iruzevic

### Added

- New feature to allow the form to be submitted only once per user.
- New feature to allow the form to be visible only when the user is logged in.

2024-11-11 14:29 UTC, piqusy requested changes
Nice work 👏🏼 

Left a few wording suggestions

2024-11-11 14:29 UTC, piqusy commented on src/Blocks/custom/forms/forms.php
> +// Check is there any reason to not render forms block.
```suggestion
// Check if is there any reason to not render forms block.
```

2024-11-11 14:29 UTC, piqusy commented on src/Validation/SettingsValidation.php
> +										'checkboxLabel' => \__('Use only for logged in users', 'eightshift-forms'),
```suggestion
										'checkboxLabel' => \__('Show only to logged in users', 'eightshift-forms'),
```

2024-11-11 14:29 UTC, piqusy commented on src/Validation/SettingsValidation.php
> +											'checkboxHelp' => \__('Use only single submit per user.', 'eightshift-forms'),
```suggestion
											'checkboxHelp' => \__('If enabled, each user can submit the form only once.', 'eightshift-forms'),
```

2024-11-12 07:14 UTC, kancijan submitted a review, later dismissed

2024-11-12 07:14 UTC, kancijan commented on src/Blocks/custom/forms/forms.php
> +// Check is there any reason to not render forms block.
```suggestion
// Check if there is any reason not to render forms block.
```

2024-11-12 07:14 UTC, kancijan commented on src/Validation/SettingsValidation.php
> +										'checkboxHelp' => \__('If form is available only for the logged in users. If the user is not logged in the form will not show.', 'eightshift-forms'),
```suggestion
										'checkboxHelp' => \__('The form will be accessible only to users who are logged in.', 'eightshift-forms'),
```

2024-11-12 07:33 UTC, kancijan approved these changes

2024-11-12 07:59 UTC, goranalkovic-infinum approved these changes

2024-11-12 08:04 UTC, merged