Adding corrections for the new HubSpot API v3
infinum/eightshift-forms pull request #467
Opened 2024-12-02 14:38 UTC by iruzevic

# Description

# Screenshots / Videos

# Linked documentation PR

2024-12-04 11:36 UTC, iobrado approved these changes

2024-12-04 13:00 UTC, iobrado submitted a review, later dismissed

2024-12-04 14:19 UTC, piqusy requested changes
Nice work 👏🏼 

Left a few suggestions

2024-12-04 14:19 UTC, piqusy commented on src/Blocks/components/date/manifest.json
> +		"datetime-local": {
How come this one has `-local` suffix and the other one doesn't?

2024-12-04 14:19 UTC, piqusy commented on src/Blocks/components/form/assets-admin/transfer.js
> +		const items = button.getAttribute(this.state.getStateAttribute('migrationExportItems'));
```suggestion
		const items = button?.getAttribute(this.state.getStateAttribute('migrationExportItems'));
```

2024-12-04 14:19 UTC, piqusy commented on src/Blocks/components/input/manifest.json
> +			"min": 0.01,
```suggestion
			"min": 0,
```
Why couldn't this be 0?

2024-12-04 14:19 UTC, piqusy commented on src/Rest/Routes/Settings/TransferRoute.php
> +							\esc_html__('Please click on the result outputs you want to export.', 'eightshift-forms'),
```suggestion
							\esc_html__('Please click on the Result outputs you want to export.', 'eightshift-forms'),
```

2024-12-05 09:52 UTC, piqusy commented on src/Integrations/Corvus/SettingsCorvus.php
> +											'checkboxHelp' => \__('Checked indicates an preauthorization. None checked indicates a sale. Note: applicable only for card transactions.', 'eightshift-forms'),
```suggestion
											'checkboxHelp' => \__('Checked indicates an pre-authorization. Unchecked indicates a sale. Note: applicable only for card transactions.', 'eightshift-forms'),
```

2024-12-05 09:55 UTC, merged