Icon refresh
infinum/eightshift-forms pull request #50
Opened 2021-02-11 17:35 UTC by goranalkovic-infinum

New icons are here! Currently set as SVG in `src`, but are also available in [Frontend libs](https://github.com/infinum/eightshift-frontend-libs/pull/284).

![image](https://user-images.githubusercontent.com/77000136/107674859-b9eb5000-6c97-11eb-8f7c-01bb39de5d44.png)

2021-02-15 09:04 UTC, IvanGrginovInf approved these changes

2021-02-15 09:05 UTC, IvanGrginovInf requested changes
Left a comment regarding spacing, otherwise looks good!

2021-02-15 09:05 UTC, IvanGrginovInf commented on src/blocks/manifest.json
> +	"foreground": "#0D3636",
@goranalkovic-infinum please fix the spacing here (here it should be 2x spaces, not a tab)

2021-04-12 12:33 UTC, IvanGrginovInf approved these changes

2021-04-12 12:34 UTC, iruzevic approved these changes

2021-04-12 12:35 UTC, merged