Fix bugs introduced by refactor
infinum/eightshift-forms pull request #60
Opened 2021-06-28 13:26 UTC by IvanGrginovInf

2021-06-28 14:30 UTC, dingo-d approved these changes
There seem to be some checks failing on the GH Actions

2021-06-29 14:15 UTC, dingo-d approved these changes

2021-07-07 12:25 UTC, dingo-d requested changes
Just fix the phpstan notices pls

2021-07-07 13:35 UTC, dingo-d approved these changes

2021-07-07 13:54 UTC, goranalkovic-infinum approved these changes

2021-07-07 13:58 UTC, merged